FROM svizor/zoomcamp-model:3.11.5-slim

RUN pip install pipenv
WORKDIR /app
COPY ["Pipfile", "Pipfile.lock", "./"]

RUN pipenv install --system --deploy --ignore-pipfile

COPY ["server.py","model1.bin","dv.bin","./"]

EXPOSE 8080

#Setting env variables for flask

ENV FLASK_APP=server.py
# Bind all IPs within the container
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8080

ENTRYPOINT ["waitress-serve", "--host=0.0.0.0","--port=8080","server:app"]