FROM svizor/zoomcamp-model:3.11.5-slim

RUN pip --no-cache-dir install pipenv
WORKDIR /app
COPY ["Pipfile", "Pipfile.lock", "./"]
RUN pipenv install --deploy --system && \ rm -rf /root/.cache
COPY ["*.py", "bank_model.bin", "./"]
EXPOSE 8080
ENTRYPOINT ["waitress", "--bind", "0.0.0.0:8080", "bank_model:app" ]